### ISSUE TITLE
关于交叉验证的问题

### ISSUE THREAD

**Issue by Hahahdamowang** [zht8506/ETDNet#1]
您好！请问您在文中的实验结果中，是分别在fold1-5进行五次实验，最后取平均的结果吗？

**Comment by zht8506** [comment]
是的，这种可以保证偶然误差更小。可以在某个flod上做实验，最后再做5折交叉验证。

Yes, this can ensure that accidental errors are smaller. You can do experiments on a certain float, and finally do 5-fold cross validation.
