### ISSUE TITLE
关于指标形式的问题

### ISSUE THREAD

**Issue by Xcy0512** [zht8506/ETDNet#2]
您在论文中使用的AP50 AP75 APs APl等指标，可以提供AP mAP FPS的各类具体指标供参考吗？

**Comment by zht8506** [comment]
FPS对于各类缺陷基本上是一样的。AP这些，是来源于标准的coco指标。各类的指标，cocoapi是没有提供的。可以使用voc格式进行训练和指标计算，注意voc计算指标时只采用了11个点，准确度不如coco的100+点，cocoapi计算的ap50会比voc的高1-2个点。
