### ISSUE TITLE
数据集使用问题

### ISSUE THREAD

**Issue by BugMaker2524** [zht8506/ETDNet#3]
您好！我最近也在做这方面的研究，但是下载的NEU-DET是没划分训练集验证集的，自己划分后效果不是很好，可不可以向您申请一下您实验所用的数据集及划分呢，百度网盘没有提取码。谢谢！我也通过邮件向您发送了请求~

**Comment by zht8506** [comment]
好的，感谢你对我们工作的关注。代码readme主要里的百度网盘链接应该有neu-det的5折划分吧。我使用的是coco格式进行训练和测试指标。
