### ISSUE TITLE
如何将txt格式转换成COCO数据集格式

### ISSUE THREAD

**Issue by helloxueen** [zht8506/ETDNet#4]
请问如何将txt格式转换成COCO数据集格式？目前的坐标点是由txt保存的，谢谢！

**Comment by zht8506** [comment]
<img width="518" alt="image" src="https://github.com/zht8506/ETDNet/assets/81303574/2068c6db-ed41-48b0-903d-0cfb4167011a">

里面有coco格式的数据集
