### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by Ryanye2000** [zht8506/ETDNet#6]
你好我可以将自己的数据集改成coco格式来用etdnet训练吗，需要修改哪些文件呢

**Comment by zht8506** [comment]
可以的，需要修改exp里的文件，可以参考YOLOX如何训练自己的数据集，我的代码框架是基于yolox的。

**Comment by zht8506** [comment]
可以的，需要修改exp里的文件，可以参考YOLOX如何训练自己的数据集，我的代码框架是基于yolox的。

**Comment by Ryanye2000** [comment]
> 可以的，需要修改exp里的文件，可以参考YOLOX如何训练自己的数据集，我的代码框架是基于yolox的。

好的，谢谢
