### ISSUE TITLE
测试自己的数据集

### ISSUE THREAD

**Issue by Ryanye2000** [zht8506/ETDNet#8]
我用etdnet训练好了自己的数据集，怎么进行测试和可视化呢

**Comment by zht8506** [comment]
tools/eval.py和tools/demo.py可以进行指标测试和可视化。此外，指标应该在训练时也会有计算。可以搜索yolox评估自己的数据集，来查看相关教程，本文框架是基于yolox的。

**Comment by Ryanye2000** [comment]
<img width="378" alt="1716796873925" src="https://github.com/zht8506/ETDNet/assets/102776028/6e22f1b8-6f20-4f33-bd1f-84f5959b7684">
我把数据集名称改完后运行demo.py报了这个错，在图片中能看到
